// Local demo: deploys mocks + engine + splitter + sLUNARRAY on a running `npx hardhat node`, runs a few epochs on
// the mock Pons curve, graduates to the mock v4 pool, drops the price so bonds are open, credits the mock escrow,
// and writes site/config.local.js.
//   npx hardhat run scripts/dev-local.js --network localhost
const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

const Q96 = 1n << 96n;
const sqrtP = (s) => BigInt(s) * Q96;
const EPOCH = 60; // 1-minute epochs for the demo
const PARAMS = { maxBonusBps: 5000, bandBps: 5000, entryBurnBps: 100, penaltyBps: 2000, releaseBps: 1000, stakingShareBps: 5000, window: 24, vestEpochs: 3, minSamples: 2 };
const mine = async (secs) => { await network.provider.send("evm_increaseTime", [secs]); await network.provider.send("evm_mine"); };

async function main() {
  const [deployer, guardian, treasury, user] = await ethers.getSigners();
  const token = await (await ethers.getContractFactory("MockERC20")).deploy();
  const sv = await (await ethers.getContractFactory("MockStateView")).deploy();
  const pm = await (await ethers.getContractFactory("MockPoolManager")).deploy(await token.getAddress(), ethers.parseEther("1000000"));
  // mock Pons curve: 1M tokens per ETH, 50 ETH of capacity so it never graduates by itself during the demo
  const curve = await (await ethers.getContractFactory("MockCurve")).deploy(await token.getAddress(), ethers.parseEther("1000000"), ethers.parseEther("1"), ethers.parseEther("1000000"), ethers.parseEther("50"));
  await token.mint(await pm.getAddress(), ethers.parseEther("500000000"));
  await token.mint(await curve.getAddress(), ethers.parseEther("500000000"));
  await token.mint(user.address, ethers.parseEther("25000000"));
  await token.mint(deployer.address, ethers.parseEther("25000000"));
  const engine = await (await ethers.getContractFactory("BondEngine")).deploy(
    await token.getAddress(), await curve.getAddress(), await pm.getAddress(), await sv.getAddress(), ethers.ZeroAddress, 0, 200, guardian.address, treasury.address, EPOCH, PARAMS);
  const escrow = await (await ethers.getContractFactory("MockEscrow")).deploy();
  const splitter = await (await ethers.getContractFactory("FeeSplitter")).deploy(await escrow.getAddress(), treasury.address, 6000);
  await splitter.setProtocol(await engine.getAddress());
  const staked = await (await ethers.getContractFactory("StakedLunarray")).deploy(await token.getAddress(), await engine.getAddress());

  // curve phase: the engine starts right away and buys back on the curve with the protocol share of the fees
  await engine.start();
  await escrow.credit(await splitter.getAddress(), { value: ethers.parseEther("10") }); // 6 to treasury, 4 to the engine
  await splitter.harvest();
  for (let i = 0; i < 3; i++) { await mine(EPOCH + 1); await engine.poke(); }
  // graduation: the curve is done and the v4 pool opens at the same price
  await curve.setGraduated(true);
  await sv.set(sqrtP(1000)); // 1,000,000 tokens per ETH
  for (let i = 0; i < 2; i++) { await mine(EPOCH + 1); await engine.poke(); }
  await escrow.credit(await splitter.getAddress(), { value: ethers.parseEther("3") }); // still pending on the escrow
  // user stakes a bit and a price drop opens bonds at ~36% discount
  await token.connect(user).approve(await engine.getAddress(), ethers.MaxUint256);
  await engine.connect(user).stake(ethers.parseEther("2000000"));
  await sv.set(sqrtP(1250));
  await mine(EPOCH + 1); await engine.poke(); // buyback happens, stakers get ETH

  const cfg = `// generated by scripts/dev-local.js — local Hardhat node only
window.BOND_CONFIG = Object.assign(window.BOND_CONFIG || {}, {
  name: "LUNARRAY",
  chainId: 31337,
  chainName: "Hardhat local",
  rpc: "http://127.0.0.1:8546",
  rpcs: ["http://127.0.0.1:8546"],
  multicall: null,
  explorer: "http://127.0.0.1:8546",
  engine: "${await engine.getAddress()}",
  splitter: "${await splitter.getAddress()}",
  token: "${await token.getAddress()}",
  staked: "${await staked.getAddress()}",
  tokenSymbol: "MOCK",
  x: "",
  treasuryBps: 6000,
  devPrivateKey: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6", // PUBLIC hardhat test key (account #3), local node only, never holds funds
});
`;
  fs.writeFileSync(path.join(__dirname, "..", "site", "config.local.js"), cfg);
  console.log("engine", await engine.getAddress(), "\nsplitter", await splitter.getAddress(), "\ntoken", await token.getAddress(), "\nstaked", await staked.getAddress());
  console.log("site/config.local.js written. Serve ./site and open it.");
}
main().catch((e) => { console.error(e); process.exit(1); });
